-- MySQL Script generated by MySQL Workbench
-- Mon Apr  4 20:54:12 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`producto` (
  `idProducto` INT NOT NULL,
  `nombre` VARCHAR(100) NULL,
  `descripcion` TEXT NULL,
  `precio` DECIMAL(5,2) NULL,
  `imagen` TEXT NULL,
  `ingredientes` TEXT NULL,
  `conservacion` TEXT NULL,
  `medidas` VARCHAR(45) NULL,
  `infoNutricional` TEXT NULL,
  PRIMARY KEY (`idProducto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`receta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`receta` (
  `idReceta` INT NOT NULL,
  `titulo` VARCHAR(200) NULL,
  `ingredientes` TEXT NULL,
  `instrucciones` TEXT NULL,
  `imagen` TEXT NULL,
  PRIMARY KEY (`idReceta`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`etiqueta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`etiqueta` (
  `idEtiqueta` INT NOT NULL,
  `etiqueta` VARCHAR(45) NULL,
  PRIMARY KEY (`idEtiqueta`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ciudad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ciudad` (
  `idCiudad` INT NOT NULL,
  `ciudad` VARCHAR(45) NULL,
  PRIMARY KEY (`idCiudad`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`cliente` (
  `idCliente` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `apellidos` VARCHAR(150) NULL,
  `email` TEXT NULL,
  `telefono` VARCHAR(45) NULL,
  `pass` TEXT NULL,
  `direccion` TEXT NULL,
  `ciudad_idCiudad` INT NOT NULL,
  PRIMARY KEY (`idCliente`),
  INDEX `fk_cliente_ciudad1_idx` (`ciudad_idCiudad` ASC) VISIBLE,
  CONSTRAINT `fk_cliente_ciudad1`
    FOREIGN KEY (`ciudad_idCiudad`)
    REFERENCES `mydb`.`ciudad` (`idCiudad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`metodoEnvio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`metodoEnvio` (
  `idMetodoEnvio` INT NOT NULL,
  `metodoEnvio` VARCHAR(45) NULL,
  PRIMARY KEY (`idMetodoEnvio`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`pedido` (
  `idPedido` INT NOT NULL,
  `importeTotal` DECIMAL(5,2) NULL,
  `cantidad` INT NULL,
  `metodoEnvio_idMetodoEnvio` INT NOT NULL,
  `cliente_idCliente` INT NOT NULL,
  PRIMARY KEY (`idPedido`),
  INDEX `fk_pedido_metodoEnvio1_idx` (`metodoEnvio_idMetodoEnvio` ASC) VISIBLE,
  INDEX `fk_pedido_cliente1_idx` (`cliente_idCliente` ASC) VISIBLE,
  CONSTRAINT `fk_pedido_metodoEnvio1`
    FOREIGN KEY (`metodoEnvio_idMetodoEnvio`)
    REFERENCES `mydb`.`metodoEnvio` (`idMetodoEnvio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pedido_cliente1`
    FOREIGN KEY (`cliente_idCliente`)
    REFERENCES `mydb`.`cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`receta_has_etiqueta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`receta_has_etiqueta` (
  `receta_idReceta` INT NOT NULL,
  `etiqueta_idEtiqueta` INT NOT NULL,
  PRIMARY KEY (`receta_idReceta`, `etiqueta_idEtiqueta`),
  INDEX `fk_receta_has_etiqueta_etiqueta1_idx` (`etiqueta_idEtiqueta` ASC) VISIBLE,
  INDEX `fk_receta_has_etiqueta_receta_idx` (`receta_idReceta` ASC) VISIBLE,
  CONSTRAINT `fk_receta_has_etiqueta_receta`
    FOREIGN KEY (`receta_idReceta`)
    REFERENCES `mydb`.`receta` (`idReceta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_receta_has_etiqueta_etiqueta1`
    FOREIGN KEY (`etiqueta_idEtiqueta`)
    REFERENCES `mydb`.`etiqueta` (`idEtiqueta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`producto_has_pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`producto_has_pedido` (
  `producto_idProducto` INT NOT NULL,
  `pedido_idPedido` INT NOT NULL,
  PRIMARY KEY (`producto_idProducto`, `pedido_idPedido`),
  INDEX `fk_producto_has_pedido_pedido1_idx` (`pedido_idPedido` ASC) VISIBLE,
  INDEX `fk_producto_has_pedido_producto1_idx` (`producto_idProducto` ASC) VISIBLE,
  CONSTRAINT `fk_producto_has_pedido_producto1`
    FOREIGN KEY (`producto_idProducto`)
    REFERENCES `mydb`.`producto` (`idProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_producto_has_pedido_pedido1`
    FOREIGN KEY (`pedido_idPedido`)
    REFERENCES `mydb`.`pedido` (`idPedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`producto_has_receta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`producto_has_receta` (
  `producto_idProducto` INT NOT NULL,
  `receta_idReceta` INT NOT NULL,
  PRIMARY KEY (`producto_idProducto`, `receta_idReceta`),
  INDEX `fk_producto_has_receta_receta1_idx` (`receta_idReceta` ASC) VISIBLE,
  INDEX `fk_producto_has_receta_producto1_idx` (`producto_idProducto` ASC) VISIBLE,
  CONSTRAINT `fk_producto_has_receta_producto1`
    FOREIGN KEY (`producto_idProducto`)
    REFERENCES `mydb`.`producto` (`idProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_producto_has_receta_receta1`
    FOREIGN KEY (`receta_idReceta`)
    REFERENCES `mydb`.`receta` (`idReceta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
